# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

env: 
  VALID_NAME: True

jobs:
  # This workflow contains a single job called "build"
  accept-changes:
    # if: github.ref_name == r'[0-9][0-9]'
    if: $VALID_NAME
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Prints the github.ref_name of the job
      - name: Print ref_name
        run: echo ${{ github.ref_name }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  
  other: 
    runs-on: ubuntu-latest

    steps: 
      - name: Does work
        run: echo does work
